sudo: false
language: node_js
node_js:
- '6.0'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
before_script:
- npm install
script:
- npm run --silent build
after_success:
- bash deploy.sh
env:
  global:
  - GH_USER: akeshavan
  - GH_REPO: akeshavan.github.io
  - secure: SV2nnOpzhbMBRmEwQ2KEv2MatOXdj7LhckPJ7ILSYk8rkYCAt06YBThhfsGsXcEIrkVQx+V04Vg4m3trV5NVFnfKM9otTRdgLvXx0GIN2frTLN/AfLgOUlQh3OPSjWFtlMbz53ewytlyNYMlajnWJhl71x0lGZ8asvTTeSPfZmIv8fNyCnSgU8IbFrrg5TUUFr9oTJO5Ey2J/4RvDaXPieWpTA6ITnVTH2gTN5aTwvjYdmb+EuBE16cgEn0k5/7Bx22EGNANGQISoB6byLFnPFPYQij1fvujSeb8isKzClXAlwX7U2D38KseBCITyvcXr26Z0ENb7unQyuDVDzMkduQ9oAK27JlfXXwk8YAI83ktXaoPCDPpTkI659qSab5VzbOqyDsvFhSJRrZ7vZ7F8xW42btxn8Rg2rGMOkrFtbjaBgXPg0dckA6CvXCJZ8xK9df4IOvQtAhHBP/dGwMrsubx3QN16zTBWr6hwqx+jLwkyRNIIEdayDgETbeBzFIH9y6lsCOlRvCWM/P6upwxFPR1M7XtS2cgXRVgdpzNpdQmPLTbqyD7V7UsyfwL8A0YMMhDTNBdFckYdj69rVmtujJ2VuW4cqGvHkp8aujSjKIssp0JBlOnFw25V4S1uv8gYLyD/Os6vNzxtjbPvurnX6ak4T8wZrEU6zoVyvaDt9c=
